---
title: "以前は、エラー出力のあるものにForkを使用していました。"
date: 2019-12-18 04:38:44
categories:
- General
tags:
- "FORKさん"
header:
  image: /assets/images/20191218043524.jpg
  og_image: /assets/images/20191218043524.jpg
---

以前は、エラー出力のあるものにForkを使用していました。ユーザーがそのサービスと対話しようとすると、実際には問題ありませんでしたが、エラーが報告されました。 Forkを使用すれば、それに対処する必要はなく、出力に必要な時間をかけることができます。それでもいい警告が出ますが、ユーザーのやり方でデータをよりきれいに処理できます。フォークには多くの利点があります。まず、ほとんどの場合にすぐに使えるインターフェイスなので、テストは非常に簡単です。第二に、その使用方法は比較的簡単で、インストールして使用を開始するだけです。第三に、多くの素晴らしいデフォルトがあります。 Pythonをまったく書かなくてもForkを実装できることを言及したいと思います。 Nodeで分岐する簡単な例を見てみましょう。小さな問題があります：const p = require（ &#39;p&#39;）const fork = require（ &#39;fork&#39;）（新しいES6インポート機能も使用できます）ノードには2つのフォークがあります。まず、標準ライブラリのドキュメントで読むことができます。 2番目は次のようになります。const r = require（ &#39;r-promise&#39;）そして、今回実装する関数は次のとおりです。const getFork =（r、_err、_result）=&gt; r.spawn（getErrorFn、null、 err：r、callback：callbackFn：_result）大したことはありませんが、そこにあるので、コードを書く必要はありません。これをコンソールで実行します：node getFork &#39;foo&#39;そして、おそらく次のような結果が得られます：function getFork（err、callbackFn、err、callback）err &amp;&amp; console.warn（ &#39;Something weird happened。&#39;）callback &amp;&amp; console .warn（callbackFn.name）console.log（ &#39;[Err] Got error：&#39;、err）console.log（ &#39;[Err] Fired callback：&#39; + callbackFn.name）callback.done（err、callbackFn）はコールバックを返します。 error（）おそらく、何か奇妙なことが起こったことを示しているのでしょう（おそらくコールバック側で何かを見逃しているのでしょう）。getErrorFnのコードからこれを見つけることができます。 F
